create table Products (
	productID VARCHAR(50),
	prodName VARCHAR(61),
	price VARCHAR(50),
	quantity INT,
	sellerId INT
);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3222Fw', 'OK Computer', '$26.77', 10, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8578VK', 'Led Zeppelin IV', '$26.29', 1, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2448js', 'Dark Side of the Moon', '$13.06', 7, 10);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6859sq', 'The Bends', '$30.99', 7, 14);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3322rF', 'Exile on Main St.', '$35.44', 7, 6);
insert into Products (productID, prodName, price, quantity, sellerId) values ('4039fV', 'At Folsom Prison', '$28.72', 0, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('4907by', 'Hotel California', '$21.62', 10, 11);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1387wm', 'Aja', '$33.02', 6, 20);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7416dB', 'The Queen Is Dead', '$37.04', 2, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9441Kg', 'Sgt. Pepper''s Lonely Hearts Club Band', '$38.67', 8, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3883HE', 'Court and Spark', '$25.82', 4, 4);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1052dL', 'Blue', '$11.29', 5, 17);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2343db', 'The Dark Side of the Moon', '$17.68', 9, 18);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8000mt', 'Blood on the Tracks', '$11.54', 3, 12);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9103po', 'The Suburbs', '$35.81', 6, 13);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7863hB', 'The Joshua Tree', '$36.02', 1, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2976dq', 'Kind of Blue', '$33.25', 4, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7983ra', 'The Velvet Underground & Nico', '$9.54', 0, 10);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9283nu', 'The Queen Is Dead', '$38.77', 8, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8505St', 'Purple Rain', '$22.70', 0, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6239CX', 'Let It Be', '$36.84', 3, 18);
insert into Products (productID, prodName, price, quantity, sellerId) values ('5093Ay', 'Blood on the Tracks', '$31.87', 4, 13);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6850yw', 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', '$23.60', 0, 12);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2691sl', 'Purple Rain', '$32.89', 2, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('4400zb', 'Sgt. Pepper''s Lonely Hearts Club Band', '$17.79', 6, 6);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2884NU', 'The College Dropout', '$36.61', 4, 18);
insert into Products (productID, prodName, price, quantity, sellerId) values ('4898iV', 'The Queen Is Dead', '$14.89', 0, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6947yt', 'Blue', '$24.41', 4, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7027Ve', 'The Suburbs', '$12.35', 0, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('4959El', 'Born to Run', '$14.17', 0, 2);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1649ul', 'Let It Be', '$18.00', 10, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3915so', 'Exile on Main St.', '$38.43', 2, 14);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7449kY', 'In the Aeroplane Over the Sea', '$9.46', 9, 4);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8267lu', 'The Chronic', '$19.38', 10, 10);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3965CY', 'The Bends', '$33.34', 9, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1688aB', 'Highway 61 Revisited', '$25.33', 4, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8787wL', 'Pet Sounds', '$17.25', 2, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3420Uj', 'Let It Be', '$33.50', 8, 9);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2539yD', 'Rumours', '$16.46', 2, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9789Df', 'Kind of Blue', '$31.55', 6, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6082XK', 'Pet Sounds', '$21.85', 7, 19);
insert into Products (productID, prodName, price, quantity, sellerId) values ('0745gY', 'The Doors', '$29.03', 9, 5);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9050OG', 'The Joshua Tree', '$24.57', 9, 4);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6415Gt', 'Hotel California', '$33.99', 1, 12);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8236dc', 'The Queen Is Dead', '$24.84', 2, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9398HN', 'Thriller', '$31.32', 7, 20);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3952xB', 'The Bends', '$30.92', 2, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2536Pc', 'Revolver', '$38.72', 10, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6655HM', 'The Wall', '$13.53', 0, 11);
insert into Products (productID, prodName, price, quantity, sellerId) values ('0431CM', 'Bridge Over Troubled Water', '$22.35', 2, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8944ln', 'In the Aeroplane Over the Sea', '$21.41', 0, 1);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6401Ne', 'The Chronic', '$32.42', 8, 2);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7877XW', 'What''s Going On', '$37.32', 7, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9497TW', 'Dark Side of the Moon', '$19.27', 3, 7);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9078Fs', 'The Queen Is Dead', '$36.97', 3, 13);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7134QD', 'The Chronic', '$16.17', 8, 17);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3836Sw', 'The College Dropout', '$17.52', 8, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8340KW', 'Purple Rain', '$25.48', 7, 6);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9734bT', 'What''s Going On', '$23.51', 5, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('4474Cq', 'Blood on the Tracks', '$17.58', 3, 4);
insert into Products (productID, prodName, price, quantity, sellerId) values ('0766jA', 'The Queen Is Dead', '$17.21', 3, 18);
insert into Products (productID, prodName, price, quantity, sellerId) values ('5779ii', 'OK Computer', '$35.32', 2, 6);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6050qg', 'Bridge Over Troubled Water', '$30.28', 3, 7);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7388Wb', 'The Low End Theory', '$21.91', 7, 16);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3273Tj', 'The Wall', '$11.76', 8, 18);
insert into Products (productID, prodName, price, quantity, sellerId) values ('0903vo', 'Born to Run', '$33.43', 3, 6);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2318zU', 'At Folsom Prison', '$31.14', 6, 6);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8738xS', 'OK Computer', '$37.10', 6, 18);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1874dG', 'Astral Weeks', '$23.55', 4, 6);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8610Gf', 'Pet Sounds', '$14.21', 5, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6564Cn', 'In the Aeroplane Over the Sea', '$27.69', 10, 12);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9200yh', 'The College Dropout', '$36.93', 8, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7943eZ', 'The Dark Side of the Moon', '$28.72', 6, 2);
insert into Products (productID, prodName, price, quantity, sellerId) values ('0036pA', 'The Chronic', '$18.42', 2, 2);
insert into Products (productID, prodName, price, quantity, sellerId) values ('5498fK', 'The Queen Is Dead', '$32.43', 4, 10);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1875YP', 'Kid A', '$32.84', 4, 20);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7368zV', 'Nevermind', '$14.03', 2, 18);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8362zx', 'Purple Rain', '$17.07', 3, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('5076cg', 'In the Aeroplane Over the Sea', '$25.16', 1, 10);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3373zC', 'London Calling', '$22.59', 9, 1);
insert into Products (productID, prodName, price, quantity, sellerId) values ('5331mS', 'The Bends', '$13.19', 10, 13);
insert into Products (productID, prodName, price, quantity, sellerId) values ('5102qx', 'At Folsom Prison', '$20.84', 3, 4);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7049xm', 'The Chronic', '$22.01', 2, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('0227EX', 'Led Zeppelin IV', '$28.39', 4, 13);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1607Dt', 'Court and Spark', '$15.10', 8, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3167fR', 'Let It Be', '$17.86', 7, 11);
insert into Products (productID, prodName, price, quantity, sellerId) values ('5512fP', 'The Wall', '$12.04', 2, 20);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2308Yc', 'In the Aeroplane Over the Sea', '$25.29', 6, 17);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9664At', 'Revolver', '$22.24', 7, 8);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6324rZ', 'What''s Going On', '$33.42', 5, 11);
insert into Products (productID, prodName, price, quantity, sellerId) values ('2512CJ', 'The Chronic', '$9.78', 4, 2);
insert into Products (productID, prodName, price, quantity, sellerId) values ('1074Zc', 'The Doors', '$20.61', 3, 11);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6644xs', 'Back in Black', '$25.89', 9, 3);
insert into Products (productID, prodName, price, quantity, sellerId) values ('3414Ps', 'Aja', '$29.32', 4, 17);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8211uf', 'The Low End Theory', '$21.48', 2, 5);
insert into Products (productID, prodName, price, quantity, sellerId) values ('9579IJ', 'Kid A', '$26.30', 9, 17);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7271kI', 'OK Computer', '$18.78', 7, 2);
insert into Products (productID, prodName, price, quantity, sellerId) values ('6775ck', 'Kind of Blue', '$37.87', 3, 14);
insert into Products (productID, prodName, price, quantity, sellerId) values ('0904bt', 'Rubber Soul', '$21.99', 9, 4);
insert into Products (productID, prodName, price, quantity, sellerId) values ('7149kQ', 'London Calling', '$14.02', 5, 15);
insert into Products (productID, prodName, price, quantity, sellerId) values ('8146AZ', 'Rubber Soul', '$17.48', 5, 11);
